services:
  postgres:
    image: postgres:latest
    container_name: postgres_recipe
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: recipe_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data_recipe:/var/lib/postgresql/data

volumes:
  postgres_data_recipe: